### ISSUE TITLE
2025. 5. 30 (음) 을 양력으로

### ISSUE THREAD

**Issue by binsoore** [usingsky/korean_lunar_calendar_py#1]
2025. 5. 30 (음) 을 양력으로

한국 천문 연구원 = 결과 없음.  
네이버 음력 변환 = 결과 없음.

korean_lunar_calendar_py 사용시 
2025-06-25로 출력.

버그 인가요?

**Comment by usingsky** [comment]
이슈 리포트 감사합니다.
음력 2025년 5월의 경우 29일까지 있어 30일은 계산해서는 안되는 날입니다.
해당 날짜 설정 시 False를 리턴해야 합니다.
계산여부를 결정하는 validation 체크에 문제가 있었습니다.
pypi에 수정하여 올렸으니 패키지를 업데이트 해보세요 (v0.2.0)

`import korean_lunar_calendar`
`calendar = korean_lunar_calendar.KoreanLunarCalendar()`
`calendar.setLunarDate(2025, 5, 30, False)`
` False`

**Comment by binsoore** [comment]
감사합니다.
