### ISSUE TITLE
Can I use this code to other places?

### ISSUE THREAD

**Issue by 1kko** [usingsky/korean_lunar_calendar_py#2]
Hi, @usingsky 
I made a plugin for python-holidays for [Korean Holidays](https://github.com/dr-prodigy/python-holidays/pull/294).

I didn't know difference between Chinese and Korean Lunar Calendar before @chongdae has reported me.

I'd like to copy some part of your code to apply my plugin.
python-holidays is MIT licensed, and also yours as far as I see in setup.py:28

I thought it was better to ask your permission before copy & paste your work,
Please let me know your thoughts.

**Comment by usingsky** [comment]
@1kko 
Thank you for letting me know. Free to use under MIT license. :)
