### ISSUE TITLE
Source tarball

### ISSUE THREAD

**Issue by fabaff** [usingsky/korean_lunar_calendar_py#5]
Can you please publish source tarballs at PyPI and here?

This became a dependency of python-holidays and to make a new release available for Fedora  I need this lib as a package. To create the package the source is needed.

Thanks.

**Comment by usingsky** [comment]
@fabaff
Thanks for your comment. I updated the library including tarball. (dist/)

**Comment by fabaff** [comment]
Thanks

Review request for Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1824269
